build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
checks:
    php: true

filter:
    excluded_paths:
        - tests/*

tools:
    external_code_coverage:
        timeout: 600
        runs: 3
